[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = {version = "0.4.0", features = ["html_reports"]}
pprof = { version = "0.3", features = ["flamegraph"] }
rand = "0.8.5"

[[bench]]
name = "benchmark"
harness = false